---
title: "MODELOS LINEALES MIXTOS"
author: "ARACELY TUESTA"
format: html
---

# pasos para analisis de datos 
1. crear mi diseño experimental = modelo estadistico
2. colectar los datos 
3. importar y verficar los factores 
4. analisi de varianza 


#librerias

```{r}
library (tidyverse)
library(googlesheets4)
library(lme4)
library(emmeans)
```

# cargar base de datos

https://docs.google.com/spreadsheets/d/15r7ZwcZZHbEgltlF6gSFvCTFA-CFzVBWwg3mFlRyKPs/edit?gid=1263018298#gid=1263018298


```{r}
url <-"https://docs.google.com/spreadsheets/d/15r7ZwcZZHbEgltlF6gSFvCTFA-CFzVBWwg3mFlRyKPs/edit?gid=1263018298#gid=1263018298"

gs <- url %>% 
  as_sheets_id()

fb <- gs %>% 
  range_read("fb") %>% 
  mutate(across(1:bloque, ~as.factor(.)))
str(fb)


```


# modelo 
$$  wue_{tuber} = \mu + bloque + riego + geno + riego * geno + e   $$
# analisis de varianza 

```{r}
md <- lmer(formula = twue ~ 0 + (1|bloque) + riego*geno                     , data = fb)




anova(md)



library(car)

Anova(md)
```

